#+INCLUDE: "./preamble.org"

#+LATEX: \maketitle

* Introduction

In popular literature, poor governance is often cited as a reason for project failure \parencite{zahreddineCouncilPostWhat2019}, and is oft considered a panacea for how to ensure IT and business strategy goals align and achieve desired synergistic impacts \parencite{lindrosWhatITGovernance2017}. However, there is a growing sense that corporate interests extend beyond the typical stakeholders of the boardroom, shareholders, employees and customers \parencite{paineGuideBigIdeas2019}, and how IT governance plays into this new understanding of corporate responsibility is a question not yet well discussed.

* Research Into IT Governance

Academic research into IT governance covers a broad range of topics. However, a large number of recent studies focus heavily on just a few specific types of questions. The first of these are the relationship between governance and firm performance. For example, \textcite{turelBoardITGovernance2019} and \textcite{hamdanITGovernanceFirm2019} both looks at how governance at the board level impacts firm performance while \textcite{haesAdoptionImpactIT2016} looks at the adoption of specific COBIT 5 framework elements and firm value. \textcite{zahreddineCouncilPostWhat2019} is an example of a popular article from that examines how governance links to growth.

Another common focus of attention is the role of governance with respect to security and risk management. This is a frequent topic in the practical ilterature \parencite{rossSixITDecisions2002,patryCouncilPostWhy2021}, but also in studies such as \textcite{mallmannAdoptionCloudComputing2018,zhangDoesSharingMake2019}.

Related to IT performance is the idea of innovation and business improvement. \textcite{herouxModeratingRoleITbusiness2018} touch on this specifically in their study which surveys senior leadership and discovers that heightened levels of governance spurs innovation regardless of the IT competence of the senior executive leadership.

A number of studies cross several of these boundaries and are really more focused on understanding the distinction played by locale, specifically how a study located in a particular industry or in a developing nation effect the impact of IT governance compared to the received current state of the literature. Examples of this sort of research include \parencite{hamdanITGovernanceFirm2019,mallmannAdoptionCloudComputing2018,kizitoInquiryITGovernance2019}.

* Areas of interest

Of particular interest are the research into role of governance into impacting security and innovation across organizational boundaries in the healthcare arena. Understanding how governance practices can make intra-organizational data-sharing more secure \parencite{zhangDoesSharingMake2019} shows real promise to provide means of generating cross-organizational value. Similarly, understanding how governance impacts new technological architectures such as cloud computing \parencite{mallmannAdoptionCloudComputing2018} is important in order to properly advise companies on how to approach these developing technologies. Lastly, understanding the interplay between IT Governance, IT competence and innovation \parencite{herouxModeratingRoleITbusiness2018} is likely important with regard to being able to properly advise corporate leadership on how and where and when to invest in IT governance capabilities over other IT capabilities and maturities.

* Key Constructs, Variables, Concepts

These articles commonly hold to a resource-based view of the firm as the most common method of describing the firm, and looked at governance as an interplay between dynamic and static constructs. There was broad agreement on the general concept of what constituted IT governance, and while no two articles described or defined the term using identical terms, it was clear the concept was employed in a common way that would be recognized across the research.

* Innovative Concepts in IT Policy and strategy

While most ideas, such as good governance improve firm value \parencite{wernickeCorporateGovernanceHow2019} are not innovative, the very idea that governance drives innovation likely is not something that most business leaders have realized or heard much about \parencite{prattRethinkingITGovernance2021}. Indeed, articles in the popular press tend to focus on how governance is seen as "boring," yet the research focuses on how it generates innovation and value, topics business leaders rarely see as lacking interest.

* Collective Call for Proactive Research

The majority of the empirical research cited relies on self-reporting by surveys. While this is a fine method for gathering initial data, and is useful for collecting a large sample set. It is limited for a variety of reasons. Most importantly, none of the studies offer a longitudinal view of any firm, so there is no ability to see the impacts of changes to governance models on performance, innovation, and other outcomes.

* Beneficial and Detrimental Topics in IT Policy and Strategy for Organizations

Of serious benefit is the insight that mature organizations can see significant increases in innovation through proper governance structures. This, combined with awareness that board-level oversight can have positive impacts under the right conditions (and negative impacts under the wrong conditions) should lead organizations to examine their IT policy structures in view of their IT capability maturity.

* A Global Perspective

While a number of the articles drew upon research from developing markets, such as Uganda and Brazil, as well as well-developed international markets such as Saudi Arabia, it can not be said that any of the studies examined truly examined IT Governance from the perspective of examining global corporations per se. As a senior leader within a global consultancy, I would expect that both our concern, and impacts of governance would be different than those of companies that operate on a more regional or national scale. None of the research spoke to the broad range of considerations that truly global corporations must contend with. However, research into emerging markets and research that focuses on the realities of governance impacts in different regions does give insight that global corporations can utilize.


\printbibliography
