#+TITLE: Key Objectives, Strategies, and Tactics for the Coming Year.
#+LATEX_HEADER: \duedate{Sep 8, 2021}
#+INCLUDE: ./preamble.org
#+LATEX: \maketitle

* Key Objectives

The various policies outlined in the policy guides as published are in support of numerous corporate objectives. These objectives are in turn supported by multiple strategies which may be achieved by various tactical plans. In particular there are two concerns that are of immediate concern for this company.

The first of these concerns is to control costs. Like many mid-sized regional insurance providers, cost controls are becoming increasingly important due to a variety of factors. Among the factors driving this need is innovations in the fintech arena creating pressures on established companies citep:bermanInnovationEntrepreneurialEcosystems2021. Therefore, a key objective for the coming year is to manage OpEx in the IT space.

The second is to ensure the secure operations of the environment. There is no question that information security plays a pivotal concern in the insurance industry, with multiple security standards impacting the industry citep:commiatoInformationSecurityStandards2018. Further, with the increasing role of artificial intelligence, machine learning, and other big-data technologies, there is growing concern from the public about responsible use of private identifying information citep:hoEnsuringTrustworthyUse2020. Therefore, providing for a continually improving information security posture is a second key objective for the corporation.


** Current State Compared to Target State

*** OpEx Reduction Needs

**** Moving to The Cloud

Currently, much of the current organization is hosted in traditional data-centers. Even with the needs of some racked systems being maintained as private cloud devices, the total cost of ownership of cloud based computing is significantly lower than the cost of ownership of maintaining private data centers in a truly robust high-availability, high-durability, disaster-recovery capable configuration citep:chiTotalCostOwnership2021. This move will allow older systems to be decommissioned, reducing costs further.

Still, due to the need to move to the cloud, this will mean that our policies will have to drive many of our systems to be re-based onto cloud-ready architecture, and it is highly likely that many of our people will need an investment in training in order to be able to be effective working with cloud technology citep:sayeghCloudTalentDrought,kenellyReasonsMostCompanies2019.

**** Strategic Partnerships and Outsourcing

The current state of the organization, from an operations expense perspective, is higher than the industry average. While this is not a policy concern, it is none-the-less a concern that can be addressed by thoughtful adoption of key policies or through the application of particular tactical measures to meet policy objectives. For example, it has been shown that efficient client-vendor management and strategic outsourcing of non-core competencies, known in the literature as boundary spanning, can itself become a core-competency of a well-functioning IT department and be an effective tool in cost reduction citep:chattopadhyayVendorBoundarySpanning2021.

*** Security Optimization

Security optimization will start with a move to true identity federation utilizing cloud technologies. There is cross fertilization here the policies that will drive a strategy of cloud-first initiatives will also improve security optimization at a lower cost.  cite:linCloudComputingInnovation2012,zhangWeKnewIt2014,awsAWSSecurityBest2016,kennedya.torkuraIntegratingContinuousSecurity2017.

Security optimization of course starts with a robust underlying process for responding to incidents in the first place. This in turn is tied to the underlying capacity to track assets, and manage the IT process itself. Thus, focusing tactically on modernizing the CMDB architecture, incident response, and the IT process board itself will provide significant gains for achieving the necessary security improvements overall.



#+LATEX: \newpage
* References
  :PROPERTIES:
  :UNNUMBERED: t
  :NEWPAGE: t
  :END:
  #+LaTeX: \printbibliography[heading=none]


#+LATEX: \newpage
* Appendix
  :PROPERTIES:
  :UNNUMBERED: t
  :NEWPAGE: t
  :END:


#+LATEX: \noindent\begin{minipage}{\linewidth}
 #+LaTeX: \centering

 #+LaTeX: \captionof{table}{Objectives, Strategies, and Tactics}
#+LATEX: \centering
 #+LaTeX: \begin{tabular}{l|l|l}
 #+LaTeX: \textbf{Objectives}                    & \textbf{Strategy}                          & \textbf{Tactics}              \\
 #+LaTeX: \hline\hline
 #+LaTeX: \multirow{6}{*}{OpEx Reduction}        & \multirow{3}{*}{Cloud Initiative}          & Training                      \\
 #+LaTeX:                                      &                                            & Rebasing                      \\
 #+LaTeX:                                      &                                            & Decommissioning               \\
 #+LaTeX: \cline{2-3}
 #+LaTeX:                                      & \multirow{3}{*}{Strategic Partnerships}    & Offshoring                    \\
 #+LaTeX:                                      &                                            & Platforming                   \\
 #+LaTeX:                                      &                                            & Externalize Non-competencies  \\
 #+LaTeX: \hline
 #+LaTeX: \multirow{6}{*}{Security Optimization} & \multirow{3}{*}{Acceptable Use Validation} & Identity Federation           \\
 #+LaTeX:                                      &                                            & Centralized Monitoring        \\
 #+LaTeX:                                      &                                            & ML Driven Auditing            \\
 #+LaTeX: \cline{2-3}
 #+LaTeX:                                      & \multirow{3}{*}{ITIL Process Management}   & CMDB Modernization            \\
 #+LaTeX:                                      &                                            & Incident Response Mgmt        \\
 #+LaTeX:                                      &                                            & IT Process Board              \\
 #+LaTeX: \hline\hline
 #+LaTeX: \end{tabular}
 #+LaTeX: \end{minipage}

