#+TITLE: Development of an Effective Centralized IT Business Process Management System


* Introduction

The pace of business change has been increasing rapidly with advancements in technology related to blockchain citep:caseBlockchainEmpiricalReview2020, cloud citep:nirenjenaCloudComputingRevolution2017, big data citep:trieuGettingValueBusiness2017, data analytics citep:dongBusinessValueBig2020, Industry 4.0 citep:sorooshianImpacts4thIndustrial2020, quantum computing, and more. Navigating such rapid and expansive changes requires an agile and responsive policy management process cite:agarwalaRolePolicyFramework2021 as being reactive is not likely to be sufficient. However, an effective process must be more than merely time efficient. It must also meet legal and regulatory requirements, provide consistent and clear guidance to employees, provide opportunities for meaningful feedback for timely course corrections and modifications, facilitate actionable oversight, ensure that policies are communicated effectively, and so forth.

The current situation for the present environment is one where individual departments are creating their own policies. These policies are stored, published, and administered locally. The result of this local control is discongrity between policies which often negatively impact not only individual employees, but the organization as a whole as uncertainty as to which policy to follow creates local inefficiencies and global confusion. Moreover, while well-intentioned directors are creating policies focused on their local department needs following the best information they have on hand; because they are not obtaining feedback from all impacted stakeholders, as well as expert legal and regulatory guidance, as the organization grows, there are multiple cases where local policies have been found to be in conflict with regulatory guidance or industry best-practices.

For these reasons, it is essential that we move to a centralized regulatory framework to ensure that we are capturing feedback from all critical stakeholders. Further, it is essential that the framework allow for rapid modifications and dissemination of policy changes across the full organization to reflect the ever-changing and rapidly evolving technological environment. This step necessary not merely because, as noted previously, the pace of business change is rapid and unfaltering, but also rapid changes in legal requirements often mandate efficient changes in corporate policy stances. For example, California's Assembly Bill 1950 created a need for companies who do business within CA to update their cybersecurity posture and policies to ensure compliance with state law cite:srivastavaRegulationPublicPolicy2021.


* The New Process outlined

Because it is the case that businesses, including our own, must be prepared to quickly re-align to adjust technologies, processes, and procedures to align to changing demands of the business environment citep:ullahBusinessInformationTechnology2017a, the process developed for managing our environment follows lean agile principles. In particular, the process is designed to be transparent to all, to limit work-in-progress, to allow open and rapid communication, and to facilitate rapid integration of empirical learnings.

** Intake

The process begins with an open intake funnel. This is an open system into which any employee can enter a proposed policy adjustment. These adjustments can be new policies, changes to existing policies, or the retirement of existing policies. The intake funnel is managed by the "product manager" of the Policy Governance Board. This role's primary responsibility is to engage the stakeholders of the proposed policy changes in the intake funnel and determine which changes have the highest business priority. Those items with the greatest business priority will be filtered to the top of the work-queue for the next step of the process. The product manager is also responsible for ensuring that the key stakeholders are appropriately identified and informed that proposed changes are in the queue.

*** Decision Point 1 (New / Change / Retire)




* a main sections

\printbibliograph

Identify a new process for creating, storing, approving, modifyi{ng, and retiring policies in the new repository.
Include a diagram or flowchart of the process in the appendix, similar to Figure 3.  Do not use this figure.
Consider who will have oversight, who will need to be involved in the process, and who are the stakeholders.  Remember that when designating accountable resources, only mention the role or job title, not incumbents (no names).
Determine how and when communication will occur.
Explain how legal, ethical, and regulatory concerns will be addressed.
Describe how the policies will be stored and published for viewing by employrees or the public, as appropriate.
Identify any other information you deem pertinent to your framework.
