#+TITLE: Development of an Effective Centralized IT Business Process Management System
#+INCLUDE: ./preamble.org
#+LATEX: \maketitle

* Introduction

The pace of business change has been increasing rapidly with advancements in technology related to blockchain citep:caseBlockchainEmpiricalReview2020, cloud citep:nirenjenaCloudComputingRevolution2017, big data citep:trieuGettingValueBusiness2017, data analytics citep:dongBusinessValueBig2020, Industry 4.0 citep:sorooshianImpacts4thIndustrial2020, quantum computing, and more. Navigating such rapid and expansive changes requires an agile and responsive policy management process citep:agarwalaRolePolicyFramework2021 as being reactive is not likely to be sufficient. However, an effective process must be more than merely time efficient. It must also meet legal and regulatory requirements, provide consistent and clear guidance to employees, provide opportunities for meaningful feedback for timely course corrections and modifications, facilitate actionable oversight, ensure that policies are communicated effectively, and so forth.

The current situation for the present environment is one where individual departments are creating their own policies. These policies are stored, published, and administered locally. The result of this local control is discongrity between policies which often negatively impact not only individual employees, but the organization as a whole as uncertainty as to which policy to follow creates local inefficiencies and global confusion. Moreover, while well-intentioned directors are creating policies focused on their local department needs following the best information they have on hand; because they are not obtaining feedback from all impacted stakeholders, as well as expert legal and regulatory guidance, as the ]]organization grows, there are multiple cases where local policies have been found to be in conflict with regulatory guidance or industry best-practices.

For these reasons, it is essential that we move to a centralized regulatory framework to ensure that we are capturing feedback from all critical stakeholders. Further, it is essential that the framework allow for rapid modifications and dissemination of policy changes across the full organization to reflect the ever-changing and rapidly evolving technological environment. This step necessary not merely because, as noted previously, the pace of business change is rapid and unfaltering, but also rapid changes in legal requirements often mandate efficient changes in corporate policy stances. For example, California's Assembly Bill 1950 created a need for companies who do business within CA to update their cybersecurity posture and policies to ensure compliance with state law citep:srivastavaRegulationPublicPolicy2021.


* The New Process outlined

Because it is the case that businesses, including our own, must be prepared to quickly re-align to adjust technologies, processes, and procedures to align to changing demands of the business environment citep:ullahBusinessInformationTechnology2017a, the process developed for managing our environment follows lean agile principles. In particular, the process is designed to be transparent to all, to limit work-in-progress, to allow open and rapid communication, and to facilitate rapid integration of empirical learnings.

** Intake

The process begins with an open intake funnel. This is an open system into which any employee can enter a proposed policy adjustment. These adjustments can be new policies, changes to existing policies, or the retirement of existing policies. The intake funnel is managed by the "product manager" of the Policy Governance Board. This role's primary responsibility is to engage the stakeholders of the proposed policy changes in the intake funnel and determine which changes have the highest business priority. Those items with the greatest business priority will be filtered to the top of the work-queue for the next step of the process. The product manager is also responsible for ensuring that the key stakeholders are appropriately identified and informed that proposed changes are in the queue.

** Legal Department (New / Change / Retire)

For proposals to change or retire existing processes, the first step after intake and prioritization is to have the legal department determine if there are any legal issues inherent in the proposed actions. For retirement proposals, legal needs to provide an affirmative support for retirement as this will be the only time that legal will have input as part of the retirement track in the interest of expediency.

For proposed changes or new processes, legal should quickly provide guidance with respect to any governing laws or regulations. This should be a first cut statement of interest. Legal will have time for deeper dives into specifics during comment periods and the framing of full drafts.

** Policy Committee

After the Legal Department has the opportunity to provide initial guidance, the policy committee, which is made up of all Department Heads, or their SME delegates, begin a time-boxed activity period to create the first draft of the proposed new policy or the draft changes for the proposed policy change. Proposed policy retirements skip this step. This step will be conducted asynchronously and it is the responsibility of the policy product owner to affirmatively ensure that stakeholder input is collected. Stakeholders may respond that they have no comment on the proposed wording, but they may not abstain from comment at all. Any failure to provide affirmative feedback will be a scorecard item for each Department's quarterly review.

** Draft Publication and Comment Period

Once the policy committee has solicited and incorporated feedback from all the Department Heads, or their designated SMEs, the Policy Product Manager will publish the draft to the policy portal as a newly proposed policy for new policies, as a policy update for modified policies, or as a rescinded policy, for retirements. For 2 additional weeks, anyone in the company may provide feedback and discussion. It is incumbent upon the Product Manager to ensure that the policy committee sees the feedback provided. For policies that impact public facing policy and are not deemed strategically sensitive, the Product Manager may elect to open up this comment period for public feedback as well. The incorporation of public feedback can be important as perceptions of public transparency surrounding policy can have salutory effects in the event of perceived or actual criminal activity by inside actors within the organization citep:jonssonRiskyBusinessCorporate2019.

This is also the period during which the Legal Department will follow up with deep research into any outstanding regulatory concerns. Legal will have the authority to flag any policies for a hold during this time period if they uncover a need for further research. It is therefore not necessary that Legal fully adjudicate any issues that they may have at this time. However, they should use this authority sparingly and with discretion. The purpose of this policy is, after all, to be responsive and allow for rapid turn-around of policy changes to be responsive to changes in the business environment.

Legal should also take this time to review policies that are being marked for retirement. If they determine that no other policies cover necessary regulatory or legal features, that should stop a policy from being retired.

** Final Edits and Adoption Period

After the comment period and final legal review completes, the Governance team will, under the Product Manager's direction, publish the policy to the policy portal. The Change Management team will be responsible for communicating the policy changes across the corporation, and working with stakeholders to establish the effective date of the policy change, be it a new policy, a policy edit, or a policy retirement.

It is recognized that often a new IT policy will require changes to technology or infrastructure to implement, or training of staff to effect well. Therefore there is no time limit imposed upon this period, as such an artificial time pressure would inevitably lead to the need for multiple exceptions almost immediately. However, all persons involved in the roll-out of policy changes should recognize that the goal is to effect change as rapidly as possible, and that the proper and successful clearance of items from this phase of the process will be a metric by which both the Change Management team and the Policy Product Manager will be measured.

** Storage

Policy documents will be stored in the corporate file store on Amazon's Cloud Simple Storage Service (S3). The bucket utilized will be segmented off into separate folders for each policy. Each policy will be readable by default by all employees unless it is determined that the policy is strategically sensitive, in which case, the governance committee and senior leadership will confer to determine which roles should have read access to the policy. The S3 bucket will have versioning turned on, and will be configured to require multi-factor authentication for deletion. This configuration means that it will require root privileges to delete any file version.

Additionally, CloudWatch will be configured to track all changes to all files within the S3 buckets containing policies, so that all changes to each file can be tracked to a specific individual. Access to make changes to policy drafts will be configured by the Policy Product Manager based on SME roles and assigned on a per-policy basis during intake as the policy moves through the process. This will ensure that role-based access is maintained. Role-based access rights for policies has been shown to be a best practice citep:dasilvaSelfAdaptiveRoleBasedAccess2017.

The S3 bucket, along with the CloudWatch logs will be configured to be multi-availability-zone, and have cross-region replication enabled. This will provide 11-9's durability (that is data loss will 1 in every 99,999,999,999 events), and 5-9's availability (that is, the files will be available for reading for 99.999% of the calendar year).

* Conclusion

The aforementioned process is lightweight and agile, allowing relatively quick changes to policy to happen when there are not significant legal or regulatory considerations impacting the policy; or when employees do not raise significant debate over technical or ethical details of a policy. However, the policy is also flexible in allowing both the legal team time to work through complex legal questions, and the Policy governance team and Change Management team time to work through tricky implementation details without undue pressure. The focus is on moving quickly while still getting things right. Still, because the process is light weight, and is intended to be kept simple and flexible, when a mistake is made, it is a simple matter for an edit to quickly follow-on. This allows changes to policy to be implemented very quickly while still receiving ample oversight. Storage is robust, durable and ensures both the availability of documentation and the security of documentation by building upon the highly robust and scalable Amazon S3 cloud service. Further, because this service provides built-in auditing capabilities and role-based access controls, it is trivial to ensure that policies remain under tight governance control while still being fully flexible in terms of who has access to read both drafts and final policy documents, as well as draft proposals.

By encouraging a transparent and open policy development system, even including the public where appropriate, this process seeks to build trust and establish an inclusive environment of cooperative policy development across the organization where all impacted individuals have their voices heard when policy is being considered.


#+LATEX: \newpage
* References
  :PROPERTIES:
  :UNNUMBERED: t
  :NEWPAGE: t
  :END:
  #+LaTeX: \printbibliography[heading=none]
