#+INCLUDE: ./preamble.org
#+LATEX: \maketitle

* Introduction
Information technology became linked to corporate governance due to the prominent role that it played within the realm of corporate finance and accounting \parencite{holderMaterialWeaknessesInformation2016,liInternalExternalInfluences2007}. Evaluating how well governance structures work in practice often utilize some form of maturity model or scoring matrix. This practice originated with ideas promulgated by Richard Nolan of Harvard University in 1973 \parencite{nolanManagingComputerResource1973}. Development on maturity models continued with military support, and a partnership between IBM, Carnegie-Mellon's Software Engineering Institute, and the US Air Force. The end result was the Capability Maturity Model framework published in the late 1980s and extended in the early 1990s \parencite{caralliMaturityModels1012012}. The goal of such frameworks is to have an objective rubric to measure the quality and maturity of a governance policy. Today it is common practice to utilize such systems and many have been developed.

* Proposed Policy Measurement matrix

In developing a matrix to evaluate a policy, one of the first decisions is what scale should be utilized for responses. The eponymous \textcite{likertTechniqueMeasurementAttitudes1932} scale, is one of the most widely used measurement scales in the social science, and seems appropriate for measuring maturity and effectiveness of a governance policy, as each statement can be categorized easily into: "never or rarely," "infrequently" "neutral or not applicable," "sometimes," and "almost always or always" or some variant of that phrasing.

** Description of the Evaluation Matrix

The evaluation matrix is based on a few simple assumptions. The first is that governance is primarily a process management activity \parencite{wilkinInformationTechnologyGovernance2020}. Thus, considerations common to quality process management are considered. Does the policy have an owner? Are the stakeholders known? Etc. Similarly, questions about the scope, enforcement, exception paths, and monitoring are asked. As with any business process, if these elements are unclear, there is little reason to suspect that the outcomes will be as valuable as the business leadership might hope. Finally, there are questions regarding the regularity of review, if the policy considers legal and regulatory demands, it's availability to those to whom it applies, and the frequency of updates. While relatively minimal, this short questionnaire provides a sound evaluation of the overall health and maturity of a policy.

* Example Application of the Matrix

Applying the matrix developed in the appendix to the Accenture, PLC Policy 0057 "Acceptable Use of Information, Devices, and Technology" (https://policies.accenture.com/policy/0057) we find that it scores reasonably well, achieving a score of 60 out of a total of 65 possible points. or just over 92%. Accenture is a consulting company based out of Dublin, Ireland with over 500,000 global employees. Last year they reported over $44B USD in revenue \parencite{accentureplcAccenture2020Annual2020}.

** Policy objectives

As stated in the policy itself, the policy objectives are "The purpose of this policy is to set forth the requirements for the protection and use of Accenture, Client and other third-party information, devices and technology." The policy achieves this goal by . . . "[setting forth] the minimum Accenture requirements when accessing any Accenture, Client, or other third-party information or technology, and when personnel use any device, while performing Accenture work."

** Expected Improvements or controls to be mitigated by the Policy

This policy mitigates risk to Accenture and Accenture's clients by minimizing risky or unwarranted use of Accenture owned devices for non-Accenture related purposes, as well as limiting use of personally owned devices on which Accenture email or data may be located.

** Policy Contents

This policy content specifically addresses: provisioning of devices; their approved uses, including both uses for Accenture business and approved personal use of Accenture owned devices; passwords and Accenture provided credentials; utilization of Accenture and Accenture client information; communication of information using email, messaging tools, collaboration tools, social media, and cloud services; physical protection of paper documents; incident reporting; compliance verification for the policy; and activities to verify compliance.

** Stakeholders and users that need to observe the Policy

The policy owner is defined as the Accenture Chief Information Security Officer. Compliance enforcement is the concern of the Computer incident response team. Legal questions are divided between the data privacy team and teh legal intellectual property team. Security exceptions are handled by the security exception team. Data and device loss or compromise of passwords or data integrity issues are handled by the Accenture security operations center. Technical support is the responsibility of the operations support team. The policy applies to all global employees and contractors.

** Evaluators and approvers of the Policy

Policy evaluation and approval is governed by Accenture policy 0001: Policy compliance, development and approval.

** Distribution and Communication and User Awareness Sessions

Policy 0057 is part of every "new joiner's" first week of orientation. It is also referenced in annual ethics and compliance training, and every employee is required to acknowledge their awareness of the content of the policy and that they are in compliance with the policy. The policy is also referenced frequently as part of device security scan pop-ups, as well as being part of the installation instructions for required software tools necessary for receiving Microsoft Teams instant messages and Exchange emails on personal phones. Additionally, it is of course published on the policy webpage. The one issue is that this policy applies to all global employees but like all Accenture policies it is translated into only a limited number of languages. This means that it is not always available in the primary language of every empoloyee to whom it applies.

** Revision History

Policy 0057 has been in continual use since July 25, 1997. All revisions since May 14, 2010 are available on-line with the policy. Revisions prior to that date are archived.

* Recommendations for Improvements

** Translations

While translations of policies are expensive, Accenture does its global employees a disservice by not having its policies available in the primary native language of all employees. The first and most critical way this, and all Accenture policies, could be improved upon is to ensure that translations are available in the primary native language of all global employees.

**  Support Documentation

For most all statements, the policy provides adequate linkage to supporting documentation. However, in a few cases there are no supporting documents. This may be because supporting documents do not exist, but in many cases, such documents do exist but links are simply not provided. For example, Policy 0056 defines password standards and should be linked to the section of this policy that requires compliance with said standards.

** Defining How Compliance Will Be Monitored.

The section on monitoring of compliance is frankly rather light weight and simply doesn't provide enough detail to determine if or how compliance with the policy should be determined. It is not clear from within the policy document itself how an interested party would determine if any given employee was in compliance with most of the provisions.

* How Does Accenture Use Policies Strategically

This is an example of a strategic policy. By having a global policy that lays out in very concrete terms how Accenture protects client information, Accenture creates an atmosphere of trust with their clients. Since Accenture must be trusted by their clients with sensative information in order to perform their role effectively, having policies that strongly outline why Accenture should be considered trustworthy is not only prudent but can be seen as a strategic.


\appendix

* Matrix Tool

#+ATTR_LATEX: :environment longtable :float
| Item                    | Never/No | Infrequent | NA | Sometimes | Always/Yes |
|-------------------------+----------+------------+----+-----------+------------|
| Does the policy have a  |          |            |    |           |          5 |
| defined owner?          |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Are the policy          |          |            |    |           |          5 |
| stakeholders defined?   |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Is the policy purpose   |          |            |    |           |          5 |
| defined?                |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Does the policy have    |          |            |    |           |            |
| any defined exceptions  |          |            |    |           |          5 |
| or exclusions?          |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Does the policy have    |          |            |    |           |            |
| defined repercussion    |          |            |    |           |            |
| for failure to comply   |          |            |    |         4 |            |
| with each requirement?  |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Does the policy define  |          |            |    |           |            |
| who is responsible      |          |            |    |         4 |            |
| for enforcement of each |          |            |    |           |            |
| element?                |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Is the policy scope     |          |            |    |           |            |
| clear?                  |          |            |    |           |          5 |
|-------------------------+----------+------------+----+-----------+------------|
| Does the policy link    |          |            |    |           |            |
| to appropriate          |          |            |    |           |            |
| supporting documents    |          |            |    |         4 |            |
| for each requirement?   |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Does the policy define  |          |            |    |           |            |
| how compliance will be  |          |            |    |           |            |
| monitored for each      |          |            |    |         4 |            |
| requirement?            |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Is the policy regularly |          |            |    |           |            |
| updated as technology   |          |            |    |           |          5 |
| or environments change? |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Is the policy readily   |          |            |    |           |            |
| available to those to   |          |            |    |         4 |            |
| whom it applies?        |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Is the policy overall   |          |            |    |           |            |
| coherent and fit        |          |            |    |           |            |
| organically with the    |          |            |    |           |          5 |
| rest of the governance  |          |            |    |           |            |
| structure?              |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
| Does the policy take    |          |            |    |           |            |
| into account legal and  |          |            |    |           |            |
| regulatory as well as   |          |            |    |           |            |
| technological           |          |            |    |           |          5 |
| limitations and         |          |            |    |           |            |
| implications?           |          |            |    |           |            |
|-------------------------+----------+------------+----+-----------+------------|
|                         |          |            |    |           |            |


\printbibliography
