#+TITLE: Innovation Management: An Overview 
#+LATEX_HEADER: \shorttitle{Innovation Management}
#+INCLUDE: "./preamble.org"
#+AUTHOR: David A. Wagle
#+LATEX_HEADER: \abstract{}
#+LATEX_HEADER: \keywords{}


* Introduction

"Innovate or die," famously attributed to management guru and author Peter Drucker, is advice taken as implicitly true. However, what does it mean to innovate in business, how is innovation related to technology, and how business managers should lead innovation are not all well understood or agreed upon. Innovation is essential to business success, and thus management must concern itself with innovation. But how to do that successfully remains the topic of robust discussion.

This paper seeks to briefly review a sampling of innovation management literature in order to ascertain commonalities to the discipline of innovation management, how innovation management relates to technology, any recurring themes present in the literature, and how innovation management relates to visionary leadership. 

* What is innovation

The Small Business Development Corporation, run by the Government of Australia parencite*:sbdcInnovationSmallBusiness2020 defines innovation in business as ". . . development and application of ideas that improve the way things are done or what can be achieved" and further offers the advice that innovation can happen in the general categories of product or service, process, marketing, and business model. textcite:pisanoYouNeedInnovation2015, in a Harvard Business Review article summarized innovation as happening along two dimension, technological changes and business model changes. In his view, all changes to products or services are ultimately technology changes, regardless of if what the underlying change is. Many additional categorizations and definitions of innovation exist in the popular press. There is clearly no extant agreement here.

As a term, "innovation" as a term has an interesting and lengthy history. In  ancient times, innovation was frequently considered a vice [[parencite:godinInnovationContestedIdea2015][part 1]]. By the Renaissance period, there were royal decrees against innovation within the public and religious sphere. Innovation had attained the status of evil (ibid, part 2). Yet those who sought to innovate started to utilize the term in a positive sense in the 19th century (ibid, part 3). By the start of the 20th century, innovation as both a term and concept had been rehabilitated to a positive meaning. According to Godin, innovators are seen as people applying creativity to address problems (ibid, p. 222-223) and drive value in both business and social contexts. The first formal academic studies of innovation started in 1890, and exploded by the 1960s. However, the current academic meaning of the term is largely attributed to Schumpter, and according to Godin rests in the notion of technological change (ibid, p. 224).  Yet despite this general agreement as to how to recognize innovation and to think of it as a positive intentional act it is still largely defying definition. Godin notes that "the absence of explicit definitions in theoretical works is a recurrent pattern" (ibid, p. 235). Godin comments on the work of Robert Buzzell and Robert Nourse from the late-1960s and contends that there are three questions that the definition of innovation must explicitly address, and for which no definitive answer has yet been produced:

- Innovation  to  whom?  First  worldwide,  first  to  a  user  or  first  to  the  market?
- Innovation in what ways (how new)? Radical or incremental?
- Innovation when? Invented or applied?

This lack of a critically accepted definition of what innovation is, presents a problem for innovation management as a practice and an academic topic. How can managers manage something that eludes agreement? How to do researchers bound a topic of study without such definition?

* Management requires measurement

A key activity for any manager is to measure that for which they are responsible. The only way managers can demonstrate that they are achieving their desired outcomes is to introduce measurements in order to establish performance baselines and against which to demonstrate changes in performance over time. Yet, a literature review of measurement in innovation management carried out in 2019 could find only a total of 17 primary studies on measurement of innovation management, out of an initial collection of 2080 studies returned by searching for relevant terms parencite:melendezLiteratureReviewMeasurement2019.  The authors note that in all of the literature examined, measurement of innovation management was contextually specific and not generalizable. There remains an academic need to establish broadly agreed upon ways of measuring innovation management.

textcite:tiddInnovationManagementContext2001 notes that this measurement problem presents a true academic challenge, as there is no clear relationship between measures of innovation and firm performance. One theory presented is that as R&D is inherently an expense, and reduces earnings per share in the short and often medium term. 

* The changing face of innovation management

While how to measure innovation isn't well understood, as is what constitutes innovation, how innovation is managed does seem to see some agreement. textcite:orttEvolutionInnovationManagement2008 notes that innovation management has gone through successive generations. Initially the R&D lab was the face of innovation, and innovation management was running that process. Innovation was "linear," a direct line from a researched discovery to a marketable product. Starting in the mid-1960's though, innovation management became focused on meeting customer needs rather than technological progress. Innovation became multidisciplinary and focused on utilizing marketing and sales to determine market needs and customer expectations. Starting in the 1970s, innovation became integrated into corporate strategies. Management of innovation now included managing knowledge and communication networks with internal staff and external partners focusing on building feedback loops to align technology with market needs. While feedback loops are present, the process of innovation remained sequential.

The 1990s saw innovation take a qualitative leap, with processes becoming iterative and parallel. Moreover, external partners become much more central to innovation management as innovations of business systems, such as supply chains, required coordinating multiple organizations and multiple levels from leadership intent and vision across companies to technological systems integration across and between companies. Structurally organizations move away from departments and towards team based approaches. Projects for innovation in the old R&D sense are being replaced by innovation being a normal component of team and corporate goals. Innovation is now becoming part of the business context. While proper R&D labs still exist and serve important functions, innovation has become inherently segregated from invention. Innovation management is seen as making contextually appropriate choices to further corporate strategy in both big and small ways by focusing on utilizing corporate resources to drive value delivery (ibid).

To date, however, there is no academic consensus of how to manage innovation. Researchers "have failed to provide a comprehensive framework to guide innovation research or management practice" parencite:tiddInnovationManagementContext2001. Tibbs points out that context strongly impacts innovation management. He argues that "no single organizational structure is effective in all circumstances, and that instead there is an optimal organizational structure that best fits a given contingency".  Innovation is differentiated, in Tibbs view, by two dimensions, uncertainty and complexity. These dimensions interact with the industry sector, the size of the company, and the current business context to provide managers of innovation the basis for how to best structure their innovation strategy. For example, problems with low uncertainty and low complexity in highly competitive industry segments likely mean that market alignment is the most important factor innovation managers have to worry about. After all, the competition is likely to be focused on substantially similar problems. On the other extreme, are projects of high uncertainty in a new domain requires flexibility, quick adaptation, and iterative learning patterns. In this context, market alignment is likely not well understood, instead the focus is on creating a market where none currently exists. An example of this would be Sony's development of the Walkman, the first commercially successful portable audio player.

In environments that are highly complex and highly uncertain, decentralized decision making, failing quickly, and parallel, even duplicative, efforts presents the most successful strategy cite:drakemanRiskDeRiskingInnovation2020. The authors in this research look at biotechnology and pharmaceutical industries looking to create breakthrough new drugs. Across the industry this generates better results at a lower cost (ibid.) Still, as this research shows, it is not the case that these innovative companies all succeed. Indeed, while the biotech industry as a whole is highly profitable, many, if not most companies fail, due to the uncertainty and ambiguity they face. It is in the aggregate that innovation succeeds, but each individual firm can be highly innovative, but still commercially unviable.   

* The role of managerial vision

While vision is a critical aspect of business leadership at all levels, it is imperative at the level of strategy for a company that wishes to be innovative. After all, innovation is focused on change, large or small, and will impact the business model sooner or later. Thus innovation management must incorporate change management, and for change management to work, leadership vision must be compelling and well communicated cite:appelbaumBackFutureRevisiting2012,kotterLeadingChange2012.

If management has a vision of innovation, that vision can drive success by pointing to a strategy characterized by strategic risk management and psychological safety. Research has shown that providing an environment that is psychologically safe, where learning behaviors and openly talking about errors and failures provides for better innovation outcomes. This environment must be created through managerial action in alignment with a vision of experimentation and learning parencite:anderssonOrganizationalClimatePsychological2020.


* The role of technology in innovation management

Scholars have identified that technology and related industries evolve in different stages. One way of defining these stages is by how technology drives innovation. Referred to in some literature as "emergence, shakeout and maturity" these epochs of change reflect different relationships between technology and innovative changes. In the earliest phases, firms are experimental with respect to technologies, as there is uncertainty with regard to the rate of technology adoption and the ability of particular technologies to drive market response. During the next era, there is consolidation to a smaller number of firms utilizing proven technologies. Innovation in technology slows during this phase while innovation in processes increase. Firms seek not to find new applications of the technology but to refine the existing technology and maximize firm efficiencies to compete in the market. During the final stages, the market is stabilized, innovation in both technology and processes decline, and innovation shifts to focusing on economies of scale to extract as much market values as possible from the remaining life of the technology parencite:shaneHandbookTechnologyInnovation2009.

Technology can play multifaceted roles throughout this life-cycle. At the early stages, innovation management needs to focus on allowing experimentation driving new ways of using technology and exploring multiple possible technology solutions to identified problems parencite:drakemanRiskDeRiskingInnovation2020. But as the technology is adapted, and the shift moves to organizational innovation in order to maximize value production parencite:volberdaManagementInnovationManagement2013, the technology involved shifts as well. Organization change still requires using technology in new ways in order to effect the desired change. But it may be using well-understood technologies in new ways.

As an example of this, consider Henry Ford's development of the assembly line. While modern operations managers rarely consider it, each component of the assembly line employees a number of technologies. Engines to turn wheels that turn drive belts that move parts along are all themselves technological innovations from bygone eras. Ford invented none of these components, but in combining well-established technologies in a new an innovative way, he changed the face of manufacturing forever. So, even when the focus of innovation shifts from inventing or developing new technology to how to build organizational efficiencies, technology (both newly developed and deeply established) remains an intrinsic consideration.

\printbibliography
